### ISSUE TITLE
最近研究区块链，有一些疑问，很不清晰，求大神给点解释吧。

### ISSUE THREAD

**Issue by janryWang** [gguoss/gguoss.github.io#1]
- 区块链具体的数据结构是啥？为什么要这么设计？
- 一个交易在区块链中所涉及的链路流程是怎样的？
- 挖矿在区块链中所涉及的链路流程是怎样的？
- 大家所说的基于区块链的扩展应用具体是什么，都是怎么扩展的？

**Comment by gguoss** [comment]
- 以bitcoin, ethereum 为列， 他们的数据结构是， 块 包含块头和该块的交易 。 设计的目的是这样的结构容易共识。 交易在区块链中是基本单元， 极端情况下， 可以以每个交易产生共识。 
- 构造交易（填充数据和代码，如签名）--》向网络发送交易 --》进入交易池 --》打包验证交易 --》共识完成，交易永久存入区块链的某一个块中。
- 打包区块， 计算区块难度以及挖矿需要的参数 --》传给挖矿模块 --》挖矿工作量证明迭代计算, 直到产生符合要求的nonce --》 把结果传回共识模块 --》 共识产生区块并全网广播
- DAPP, 分布式应用， 如以去中心化交易所， 0x, etherdelta不需要中心化交易所人做担保，做中间人， 而是通过链做担保，做中介。

**Comment by janryWang** [comment]
更细一点的讨论

第一个问题，A区块高度100,B区块高度99，现在是B区块里会记录A区块的HASH，能不能让A区块里记录B区块的HASH？

第二个问题，交易这一部分，是不是给定A,B两个地址，需要从A中转账至B，首先经历钱包客户端，将A地址与签名传给钱包客户端，钱包客户端发送异步请求给P2P网络节点客户端(钱包客户端不作为具体网络节点)，节点客户端收到请求，找到当前新产出的区块，引用当前最新区块的有效未花费输出来计算当前新交易的未花费输出，并产生脚本，节点客户端验证该脚本，如果合法则广播至全网，直到6个节点确认完毕，则将交易信息存储至区块中，并广播至全网，如果您认可我上面所说的，那么这里有两个点还不太清晰：
- 交易都是在最新的区块内处理的吗？
- 有效未花费输出永远都是由上一笔交易计算出来的吗？这样做就是为了解决双花问题吗？还是解决双花问题其实仅仅只是利用6次确认来避免双花？

第三个问题：挖矿和其他任何一个基于区块链的操作是不是都是以交易的形式存在？比如挖矿作为一个coinbase交易，基于侧链的转账是不是也是一笔特殊交易？之前看过一些文章，说侧链转账需要有一个锁定操作，这个锁定操作是不是也是一个交易类型？实现一个侧链转账的确认流程是否要经历两个主链的确认流程才释放锁定操作？

第四个问题与第三个问题比较相似，应该都是以侧链来扩展的，但是侧链具体是不是也是一个区块链，还是仅仅只是一个两个主链之间的转换协议？

**Comment by gguoss** [comment]
第一个问题： 只有较高高度的区块可以存之前的HASH, Hash 是摘要算法。 只能对以前的已经产生的区块做存储。 然后现在区块链的区块记录都是从低高度区块往高高度区块生长。

**Comment by gguoss** [comment]
第二个问题： 你所描述的是一种方案（虽然我没看到你所描述的方案应用）， 然后你所描述应该是比特币相关区块链。 钱包和链是两个东西， 是异步的，签名之后发出交易不用6个节点确认。 你对交易签名之后， 交易就会广播了， 广播之后， 交易能on-chain, 你才能查到你交易成功与否。 或者你的交易在固定的时间内没有在区块链中的某个块中， 那么你的交易会被全网丢弃。 你的钱包一般是轮询链的各个区块，看有没有你的交易在里面，来确认你交易有没有上链。 UTXO除了Coinbase的交易和genesis中的交易， 其余类型的交易都是之前的UTXO移交过来。 你所说的上一笔应该是和该UTXO相关的上一笔。 这样能够解决双花问题。6次确认，只是约定的一个现在相对很安全的一个系数。

**Comment by gguoss** [comment]
第三个问题：挖矿和交易没有你所说的和交易形式相关， 只是挖矿时需要给矿工一定的激励（区块的奖励和交易手术费）。 现在比特币还没有側链， 当然你设计一笔特殊交易作为跨链是一种方案。 锁定操作是属于一笔交易， 一般通过锁定hash来实现的跨链，需要你所说的多链确认过程。

**Comment by gguoss** [comment]
側链也是一个区块链， 后面也会产生两个主链的转换协议， 比如，polkadot, cosmos, interledge等就是跨链协议中的优秀协议

**Comment by janryWang** [comment]
我有看过你的博客文章，有专门介绍UTXO模型的，这个模型具体就是在交易链中借助UTXO这个数值单位来做各种校验的一个逻辑，对吧？好像现在使用UTXO模型的币种有点少了，很多都采用了Account模型，两者的优劣能简单描述一下吗？

**Comment by gguoss** [comment]
UTXO 更类似于函数式编程， 如haskell。  Account 更类似于我们的面向对象编程， 如JAVA

**Comment by gguoss** [comment]
UTXO有天然的防双花功能 = Account + Nonce。  基于UTXO的币种有很多， 比如btc, ada。 基于账户模型的是ethereum之类。

**Comment by gguoss** [comment]
基于UTXO模型， 如函数式编程一样， 起点高， 理解困难，不易人为编程， 但设计漂亮。 基于Account模型， 面向普通大众， 能快速产业化

**Comment by janryWang** [comment]
很感谢这么耐心的回答我的问题，现在我还有一些不太明白的地方，就是任何一个交易模型中，手续费是如何与矿工挖矿的奖励挂钩的呢？现在不管是以太坊还是比特币，好像在转账的过程中都会存在一些手续费

**Comment by gguoss** [comment]
比特币会把一个块中所有交易的手续费放到该块的的coinbase交易中，coinbase是每个比特币区块必须包含的交易， 它同时包含了挖矿奖励和该块的所有交易手续费。 
以太坊是账户模型，同样把该挖矿奖励和该块的交易手续费直接对矿工的账户状态进行更新。

**Comment by zcm211** [comment]
大佬你二维码被拉伸了，无法扫码打赏
