### ISSUE TITLE
Tendermint+Ethermint 验证节点和账号是如何绑定的？如何将奖励给到节点账户

### ISSUE THREAD

**Issue by nchennan** [gguoss/gguoss.github.io#2]
郭大侠，请教个问题 我现在使用Tendermint+Ethermint，发现节点和账户是没有绑定的，所以区块奖励它给到了0x0000000000000000000000000000000000000000，也就是没有实现节点奖励，Tendermint为什么没有设计节点奖励呢？如果我们要实现节点奖励，是不是需要初始化时，先创建账号，然后修改程序将节点和账号绑定，然后在确认区块打包完成时，进行对应的奖励？即验证节点和账号是如何绑定的？如何将奖励给到节点账户？如果不使用这种方式，有其它方式吗？希望得到您的帮助，谢谢

**Comment by gguoss** [comment]
cosmos的节点奖励， 正在更新中， ethermint 只是他们试用的一个小玩具。 tendermint 实现收费可以参考https://github.com/cosmos/cosmos-sdk/tree/master/x/auth
